---
title: My favorite quotes from Rubyfruit Jungle 
author: "Trang Nguyen"
date: "2021-07-18"
tags:
  - reading
  - book notes
desciption: Rubyfruit Jungle quotes
output: html_document
# draft: True
# need to add picture, look into book review templates
---

This was my first fiction read in a long time and it was a prefect book to return to. Some of the best quotes from the book are:

> “Is this relationship with Faye Raider of an, uh—intimate nature?” “We fuck, if that’s what you’re after.”

This pretty much sums up the protagonist's personality: outspoken and secure with herself. 

> I began to wonder if girls could marry girls, because I was sure I wanted to marry Leota and look in her green eyes forever. But I would only marry her if I didn’t have to do the housework. I was certain of that. But if Leota really didn’t want to do it either, I guessed I’d do it. I’d do anything for Leota.

> "There’s no security with a woman.” “Hell, you married a man and you didn’t have money. And security—you’re secure when you’re dead.”

Expecting security from a marriage is a classic patriarchial belief. Equating security with money might be true in the short term, but definitely not for long.

> "It doesn't matter to me. We're still cousins in our own way. Blood's just something old people talk about to make you feel bad."

Brown's writing is so simple yet powerful, which is not always easy to do, let alone doing consistently. To defy familial bond is a scandalous and dangerous thing to do, especially in the conservative society of 1970s.

> “Are you married yet?” “Don’t you remember? I told you when we were kids that I was never getting married. I kept my promise.” “Oh, you just haven’t met the right man.” Nervous laugh. “Right. Everybody says that but it’s a load of shit.”

Nothing an appropriate amount of cursing can't convey.